volumes:
  postgres_data:

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
    networks:
      - iam_network

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    restart: always
    command:
      - start-dev
      - --db=postgres
      - --db-url=jdbc:postgresql://postgres/keycloak
      - --db-username=keycloak
      - --db-password=password
      - --http-relative-path=/auth
      - --hostname-strict=false
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_FEATURES: scripts
      KC_AUTHORIZATION_ENABLE_SCRIPT_UPLOAD: "true"
    ports:
      - "8180:8080"
    depends_on:
      - postgres
    volumes:
      - ./keycloak-data:/opt/keycloak/data
    networks:
            - iam_network
networks:
        iam_network:
                driver: bridge



