volumes:
  postgres_data:

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
    networks:
      - iam_network

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    restart: always
    command:
      - start-dev
      - --db=${KC_DB}
      - --db-url=${KC_DB_URL}
      - --db-username=${KC_DB_USERNAME}
      - --db-password=${KC_DB_PASSWORD}
      - --http-relative-path=/auth
      - --hostname-strict=false
    environment:
      KC_DB: ${KC_DB}
      KC_DB_URL: ${KC_DB_URL}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_FEATURES: scripts
      KC_AUTHORIZATION_ENABLE_SCRIPT_UPLOAD: "true"
    ports:
      - "8180:8080"
    depends_on:
      - postgres
    volumes:
      - ./keycloak-data:/opt/keycloak/data
    networks:
      - iam_network

networks:
  iam_network:
    driver: bridge

